[workspace]
members = [
  "dbutils",
  "indexsort",
]
resolver = "2"

[workspace.package]
repository = "https://github.com/al8n/layer0"
edition = "2021"
rust-version = "1.56.0"
homepage = "https://github.com/al8n/layer0"
categories = ["asynchronous", "data-structures", "concurrency", "database-implementations", "development-tools"]
license = "MIT OR Apache-2.0"

[workspace.package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
