[package]
name = "dbutils"
version = "0.3.1"
repository.workspace = true
edition.workspace = true
rust-version = "1.56.0"
homepage.workspace = true
categories.workspace = true
license.workspace = true
metadata.workspace = true
description = "Utils for developing database"

[features]
default = ["std"]
alloc = ["cheap-clone/alloc"]
std = ["cheap-clone/default"]

[dependencies]
cheap-clone = { version = "0.1", default-features = false }
