[package]
name = "dbutils"
version = "0.3.2"
repository.workspace = true
edition.workspace = true
rust-version = "1.56.0"
homepage.workspace = true
categories.workspace = true
license.workspace = true
metadata.workspace = true
description = "Utils for developing database"

[features]
default = ["std"]
alloc = ["cheap-clone/alloc"]
std = ["cheap-clone/default"]

bytes = ["cheap-clone/bytes"]
either = ["cheap-clone/either"]
smol_str = ["cheap-clone/smol_str"]
faststr = ["cheap-clone/faststr"]

[dependencies]
cheap-clone = { version = "0.1", default-features = false }
