[package]
name = "dbutils"
version = "0.3.8"
repository.workspace = true
edition.workspace = true
rust-version = "1.56.0"
homepage.workspace = true
categories.workspace = true
license.workspace = true
metadata.workspace = true
description = "Utils for developing database"

[features]
default = ["std"]
alloc = ["cheap-clone/alloc"]
std = ["cheap-clone/default", "crc32fast?/std", "xxhash-rust?/std"]

bytes = ["cheap-clone/bytes"]
either = ["cheap-clone/either"]
smol_str = ["cheap-clone/smol_str"]
faststr = ["cheap-clone/faststr"]

crc32 = ["crc32fast"]
xxhash64 = ["xxhash-rust/xxh64"]
xxhash3 = ["xxhash-rust/xxh3"]


[dependencies]
cheap-clone = { version = "0.1", default-features = false }

crc32fast = { version = "1", optional = true, default-features = false }
xxhash-rust = { version = "0.8", optional = true, default-features = false }

[dev-dependencies]
rstest = "0.22"
